Shopstagram/Controllers/AddReviewController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Shopstagram.Domain;
using Shopstagram.Domain.Models;

namespace Shopstagram.Controllers
{
    public class AddReviewController : Controller
    {
        //
        // GET: /AddReview/

        private readonly ICategoryProvider _categoryProvider;

        public AddReviewController(ICategoryProvider categoryProvider)
        {
            _categoryProvider = categoryProvider;
        }


        public ActionResult AddReview(string token)
        {
            var ownedProducts = _categoryProvider.GetOwnedProducts();
            var modelList = ownedProducts.Select(x => x.ToModel()).ToList();
            TempData["productModel"] = modelList;
            return View(new AddReviewModelWrapper(modelList, token));
        }

        public class AddReviewModelWrapper
        {
            public IList<ProductModel> List { get; set; }
	        public string Token { get; set; }

            public AddReviewModelWrapper(IList<ProductModel> list, string token)
            {
                List = list;
	            Token = token;
            }
        }

    }
}

Shopstagram/Controllers/HomeController.cs
using System.Configuration;
using System.Web;
using System.Web.Mvc;
using Shopstagram.Common;
using Shopstagram.Domain;

namespace Shopstagram.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
	        return View("close");

        }
    }
}

Shopstagram/Controllers/ImageUploadController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shopstagram.ApiAccess;
using Shopstagram.Domain;
using Shopstagram.Domain.Models;

namespace Shopstagram.Controllers
{
    public class ImageUploadController : Controller
    {
        //
        // GET: /FileUpload/

        private readonly IImageHandler _imageHandler;
        private readonly IUserProvider _userProvider;
        private readonly ITokenProvider _tokenProvider;

        public ImageUploadController(IImageHandler imageHandler,IUserProvider userProvider, ITokenProvider tokenProvider)
        {
            _imageHandler = imageHandler;
            _userProvider = userProvider;
            _tokenProvider = tokenProvider;
        }

        public ActionResult Upload(long id, string token)
        {
            TempData["id"] = id;
            return View();
        }

        public ActionResult Save(FormCollection formCollection)
        {
            if (TempData["productModel"] != null && TempData["id"] != null)
            {
                var products = (List<ProductModel>)TempData["productModel"];
                var id = (long) TempData["id"];

                var product = products.First(x => x.Id == id);

                if (Request != null)
                {
                    var currentUser = _userProvider.GetCurrentUser();
                    HttpPostedFileBase file = Request.Files["UploadedFile"];
                    _imageHandler.SaveImage(file, Server.MapPath("/static/saved/"), product, currentUser);
                }
                return RedirectToAction("Index", "Landing", new {token = _tokenProvider.Token});
            }

            return View("Error");

        }

       

    }
}

Shopstagram/Controllers/LandingController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shopstagram.ApiAccess;
using Shopstagram.Common;
using Shopstagram.Domain;
using Shopstagram.Domain.Models;

namespace Shopstagram.Controllers
{
    public class LandingController : Controller
    {

        private readonly IReviewedProductProvider _reviewedProductProvider;
		private readonly IConfigurationProvider _configurationProvider;

        public LandingController(IReviewedProductProvider reviewedProductProvider, IConfigurationProvider configurationProvider)
        {
	        _reviewedProductProvider = reviewedProductProvider;
	        _configurationProvider = configurationProvider;
        }

	    //
        // GET: /Landing/

        public ActionResult Index(string token)
        {
            var allReviewdItems = _reviewedProductProvider.GetAllReviewdItems();
			return View(new LandingModelWrapper(_configurationProvider) { ItemList = allReviewdItems.Select(x => x.ToModel()).ToList(), Token = token});
        }

        public class LandingModelWrapper
        {
	        private readonly IConfigurationProvider _configurationProvider;

	        public LandingModelWrapper(IConfigurationProvider configurationProvider)
	        {
		        _configurationProvider = configurationProvider;
	        }

	        public IList<ReviewedItemModel> ItemList { get; set; }
	        public string Token { get; set; }
			public string AppId {
				get { return _configurationProvider.AppId; }
			}
	        public string BaseUrl { 
				get { return _configurationProvider.BaseUrl; }
	        }
        }

    }
}

Shopstagram/Views/AddReview/AddReview.cshtml
@using Microsoft.Ajax.Utilities
@model Shopstagram.Controllers.AddReviewController.AddReviewModelWrapper
@{
    ViewBag.Title = "AddReview";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        .container {
            margin: auto 80px;
        }

        .square {
            width: 300px;
            height: 300px;
            float: left;
            margin: 15px;
            background-size: cover;
        }

        .inner {
            margin: auto 20px;
        }
    </style>
</head>
    <body onload="addImages();">
        <div class="container">
            @foreach (var item in Model.List)
            {
                <div id="@item.Id" class="square" onclick="uploadNewImagePage(@item.Id)">
                    <div class="inner">@item.ProductName</div>
                </div>
            }
        </div>
        <script type="text/javascript">
            function addImages() {
                var ids = [@Html.Raw(String.Join(",", Model.List.Select(i => "'" + i.Id + "'")))];
                var images = [@Html.Raw(String.Join(",", Model.List.Select(i => "'" + i.ImageUrl + "'")))];
                for (var i = 0; i < ids.length; i++) {
                    document.getElementById(ids[i]).style.backgroundImage = 'url(' + images[i] + ')';
                }
            }

            function uploadNewImagePage(id) {
            	window.location.href = '/ImageUpload/Upload?id=' + id + '&token=@Model.Token';
            }
        </script>
    </body>
</html>

Shopstagram/Views/Home/close.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
	<head>
		<title>title</title>
	</head>
	<body>
		<<script type="text/javascript">
 			window.close();
 		</script>
	</body>
</html>

Shopstagram/Views/Home/index.cshtml
@model Shopstagram.Controllers.LandingController.LandingModelWrapper
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        .container {
            margin: auto 80px;
        }

        .square {
            width: 300px;
            height: 300px;
            float: left;
            margin: 15px;
            background-size: cover;
        }

        .inner {
            margin: auto 20px;
        }
    </style>
</head>
    <body onload="addImages();">
        <ul><li><a href="/AddReview/AddReview?token=@Model.Token">Add New</a></li><li><a href="#">View yours</a></li></ul>
        <div class="container">
            @foreach (var item in Model.ItemList)
            {
                <div class="square" >
                    <div class="inner">@item.Id</div>
                </div>
            }
        </div>
        
        <script type="text/javascript">
            function addImages() {
                var ids = [@Html.Raw(String.Join(",", Model.ItemList.Select(i => "'" + i.Id + "'")))];
                var images = [@Html.Raw(String.Join(",", Model.ItemList.Select(i => "'" + i.UploadedUrl + "'")))];
                for (var i = 0; i < ids.length; i++) {
                    document.getElementById(ids[i]).style.backgroundImage = 'url(file://' + images[i] + ')';
                }
            }
        </script>
    
        @RenderBody()
    </body>
</html>

Shopstagram/Views/ImageUpload/upload.cshtml
@{
    ViewBag.Title = "upload";
}

<h2>upload Image</h2>
   @using(Html.BeginForm("Save", "ImageUpload", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
<table>
<tr>
<td>Image:</td>
<td>
    <input type="file" name="UploadedFile" />
</td>
</tr>
<tr>
<td colspan="2">
<input type="submit" name="Submit" value="Submit"/>
</td>
</tr>
</table>
}

Shopstagram/Views/Landing/index.cshtml
@model Shopstagram.Controllers.LandingController.LandingModelWrapper
@{
    ViewBag.Title = "Home Page";
//    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <style type="text/css">
        .container {
            margin: auto 80px;
        }

        .square {
            width: 300px;
            height: 300px;
            float: left;
            margin: 15px;
            background-size: cover;
        }

        .inner {
            margin: auto 20px;
        }
    </style>
</head>
	<body onload="addFileImages();">
@*		<ul><li><a href="@Model.BaseUrl/app/@Model.AppId/l/AddReview/AddReview">Add New</a></li><li><a href="#">View yours</a></li></ul>*@
		<ul><li><a href="/AddReview/AddReview?token=@Model.Token">Add New</a></li><li><a href="#">View yours</a></li></ul>
		<div class="container" >
			@foreach (var item in Model.ItemList)
			{
				<div id="@item.Id" class="square" style="background-image: url(@item.UploadedUrl)">
					<div class="inner">@item.Id</div>
				</div>
			}
		</div>
    
	</body>
</html>

Shopstagram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>